### ISSUE TITLE
Error in building, starting Llamafactory

### ISSUE THREAD

**Issue by mejdi1** [NVIDIA/RTX-AI-Toolkit#3]
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Containerfile
#1 transferring dockerfile: 1.56kB done
#1 DONE 0.0s

#2 [internal] load metadata for nvcr.io/nvidia/ai-workbench/python-cuda122:1.0.3
#2 DONE 0.6s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [ 1/17] FROM nvcr.io/nvidia/ai-workbench/python-cuda122:1.0.3@sha256:cbb38952edbcf34bd0bae5ae0d3fb333c27d083cc052b237a2b3207cd6ed85fd
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 3.90kB done
#5 DONE 0.0s

#6 [ 3/17] RUN groupadd -g 1000 workbench || true
#6 CACHED

#7 [10/17] RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y     wget
#7 CACHED

#8 [ 4/17] RUN useradd -u 1000 -g 1000 -rm -d /home/workbench -s /bin/bash workbench || usermod -l workbench $(getent passwd 1000 | cut -d: -f1)
#8 CACHED

#9 [ 6/17] RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y     sudo
#9 CACHED

#10 [ 8/17] COPY --chown=1000:1000  [preBuild.bash, /opt/project/build/]
#10 CACHED

#11 [14/17] RUN pip install --user     -r /opt/project/build/requirements.txt
#11 CACHED

#12 [11/17] RUN dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; wget -O- https://github.com/tianon/gosu/releases/download/1.17/gosu-${dpkgArch} | install /dev/stdin /usr/local/bin/gosu
#12 CACHED

#13 [12/17] COPY  --chmod=755 [entrypoint.sh, /]
#13 CACHED

#14 [ 7/17] RUN echo "workbench	ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/workbench
#14 CACHED

#15 [ 5/17] RUN mkdir -p /mnt/huggingface/ && chown 1000:1000 /mnt/huggingface/
#15 CACHED

#16 [ 9/17] RUN ["/bin/bash", "/opt/project/build/preBuild.bash"]
#16 CACHED

#17 [13/17] COPY --chown=1000:1000  [requirements.txt, /opt/project/build/]
#17 CACHED

#18 [ 2/17] WORKDIR /opt/project/build/
#18 CACHED

#19 [15/17] COPY --chown=1000:1000  [postBuild.bash, /opt/project/build/]
#19 CACHED

#20 [16/17] RUN ["/bin/bash", "/opt/project/build/postBuild.bash"]
#20 0.246 
#20 0.246 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#20 0.246 
#20 0.300 Reading package lists...
#20 1.010 Building dependency tree...
#20 1.155 Reading state information...
#20 1.269 The following additional packages will be installed:
#20 1.269   python3-pip-whl python3-setuptools-whl
#20 1.295 The following NEW packages will be installed:
#20 1.295   python3-pip-whl python3-setuptools-whl python3.10-venv
#20 1.574 0 upgraded, 3 newly installed, 0 to remove and 67 not upgraded.
#20 1.574 Need to get 2473 kB of archives.
#20 1.574 After this operation, 2884 kB of additional disk space will be used.
#20 1.574 Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3-pip-whl all 22.0.2+dfsg-1ubuntu0.4 [1680 kB]
#20 5.821 Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3-setuptools-whl all 59.6.0-1.2ubuntu0.22.04.1 [788 kB]
#20 7.699 Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3.10-venv amd64 3.10.12-1~22.04.3 [5716 B]
#20 7.795 debconf: delaying package configuration, since apt-utils is not installed
#20 7.814 Fetched 2473 kB in 6s (386 kB/s)
#20 7.831 Selecting previously unselected package python3-pip-whl.
#20 7.831 (Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 15007 files and directories currently installed.)
#20 7.848 Preparing to unpack .../python3-pip-whl_22.0.2+dfsg-1ubuntu0.4_all.deb ...
#20 7.852 Unpacking python3-pip-whl (22.0.2+dfsg-1ubuntu0.4) ...
#20 7.885 Selecting previously unselected package python3-setuptools-whl.
#20 7.886 Preparing to unpack .../python3-setuptools-whl_59.6.0-1.2ubuntu0.22.04.1_all.deb ...
#20 7.890 Unpacking python3-setuptools-whl (59.6.0-1.2ubuntu0.22.04.1) ...
#20 7.916 Selecting previously unselected package python3.10-venv.
#20 7.916 Preparing to unpack .../python3.10-venv_3.10.12-1~22.04.3_amd64.deb ...
#20 7.920 Unpacking python3.10-venv (3.10.12-1~22.04.3) ...
#20 7.948 Setting up python3-setuptools-whl (59.6.0-1.2ubuntu0.22.04.1) ...
#20 7.957 Setting up python3-pip-whl (22.0.2+dfsg-1ubuntu0.4) ...
#20 7.966 Setting up python3.10-venv (3.10.12-1~22.04.3) ...
#20 10.28 Cloning into 'LLaMA-Factory'...
#20 76.35 error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
#20 76.35 error: 1568 bytes of body are still expected
#20 76.35 fetch-pack: unexpected disconnect while reading sideband packet
#20 76.35 fatal: early EOF
#20 76.35 fatal: fetch-pack: invalid index-pack output
#20 ERROR: process "/bin/bash /opt/project/build/postBuild.bash" did not complete successfully: exit code: 128
------
 > [16/17] RUN ["/bin/bash", "/opt/project/build/postBuild.bash"]:
7.920 Unpacking python3.10-venv (3.10.12-1~22.04.3) ...
7.948 Setting up python3-setuptools-whl (59.6.0-1.2ubuntu0.22.04.1) ...
7.957 Setting up python3-pip-whl (22.0.2+dfsg-1ubuntu0.4) ...
7.966 Setting up python3.10-venv (3.10.12-1~22.04.3) ...
10.28 Cloning into 'LLaMA-Factory'...
76.35 error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
76.35 error: 1568 bytes of body are still expected
76.35 fetch-pack: unexpected disconnect while reading sideband packet
76.35 fatal: early EOF
76.35 fatal: fetch-pack: invalid index-pack output
------
Containerfile:52
--------------------
  50 |     COPY --chown=$NVWB_UID:$NVWB_GID  ["postBuild.bash", "/opt/project/build/"]
  51 |     
  52 | >>> RUN ["/bin/bash", "/opt/project/build/postBuild.bash"]
  53 |     
  54 |     USER $NVWB_USERNAME
--------------------
ERROR: failed to solve: process "/bin/bash /opt/project/build/postBuild.bash" did not complete successfully: exit code: 128
Build Failed

**Comment by kedarpotdar-nv** [comment]
Hi @mejdi1 . thanks for reporting. 

Looks like the llama-factory repo failed to clone based on logs:

10.28 Cloning into 'LLaMA-Factory'...
76.35 error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
76.35 error: 1568 bytes of body are still expected

This happens with network is unstable. Could you please re-try?

**Comment by mejdi1** [comment]
hi @kedarpotdar-nv.

There is other way to build it ??

Thank you
