### ISSUE TITLE
Cuda enviorment was not detected

### ISSUE THREAD

**Issue by mejdi1** [NVIDIA/RTX-AI-Toolkit#4]
![Screenshot (1)](https://github.com/NVIDIA/RTX-AI-Toolkit/assets/116952163/b4d10aa2-d7ba-4c79-9919-fff18c170a2a)
![Screenshot (2)](https://github.com/NVIDIA/RTX-AI-Toolkit/assets/116952163/af1bb10d-52d3-45ba-bc64-7d7497fdf567)

**Comment by kedarpotdar-nv** [comment]
Can you please share the version of Docker Desktop installed on your system? And the NVIDIA Driver version? 
Thanks
